# Generated by Django 5.1.6 on 2025-03-10 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_garage'),
    ]

    operations = [
        migrations.AddField(
            model_name='garage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
