# Generated by Django 5.1.5 on 2025-03-10 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_garage_image'),
        ('myapp', '0004_remove_customer_last_login'),
    ]

    operations = [
    ]
