# Generated by Django 5.1.6 on 2025-03-13 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_merge_20250311_0307'),
    ]

    operations = [
        migrations.AddField(
            model_name='garage',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
