# Generated by Django 5.1.5 on 2025-03-13 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_car_reg_plate'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestAssistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_manufacturer', models.CharField(max_length=50)),
                ('car_model', models.CharField(max_length=50)),
                ('issue_description', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.customer')),
                ('garage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.garage')),
            ],
        ),
    ]
