# Generated by Django 5.1.6 on 2025-03-14 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_requestassistance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RequestAssistance',
        ),
    ]
