# Generated by Django 5.1.6 on 2025-03-14 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='garage',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.garage'),
        ),
    ]
