# Generated by Django 5.1.5 on 2025-03-16 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_customer_garage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('available', 'Available'), ('assigned', 'Assigned')], default='available', max_length=10)),
                ('current_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.request')),
                ('garage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.garage')),
            ],
        ),
    ]
