# Generated by Django 5.1.6 on 2025-03-17 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_worker_email_alter_worker_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
