# Generated by Django 5.1.5 on 2025-03-17 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_worker_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.worker'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='current_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_worker', to='myapp.request'),
        ),
        migrations.CreateModel(
            name='ServiceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('service_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('garage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.garage')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.request')),
                ('worker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.worker')),
            ],
        ),
    ]
