# Generated by Django 5.1.5 on 2025-03-17 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_request_worker_alter_worker_current_request_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='myapp.worker'),
        ),
    ]
