# Generated by Django 5.1.6 on 2025-03-18 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
